# Generated by Django 2.1.7 on 2019-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='img',
            field=models.ImageField(default='media/default.BMP', upload_to='media'),
        ),
    ]
