# Generated by Django 2.1.7 on 2019-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_addproduct_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='Category',
            field=models.CharField(choices=[('Dresses', 'Dresses'), ('Blouses', 'Blouses'), ('T-shirts', 'T-shirts'), ('OutWare', 'OutWare'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
