# Generated by Django 2.1.7 on 2019-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_technicalsuppoertmessages_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupportticket',
            name='is_open',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
